---
# When ConfigMap changes we must rollout pods:
# kubectl rollout restart deploy/<name>
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-marco-polo-config
data:
  PORT: "3000"
  NODE_ENV: "staging"
  LOG_LEVEL: "debug"
  LOG_FORMAT: "json"
  MARCO_URL: "http://marco-service:3000/api/marco"
  POLO_URL: "http://polo-service:3000/api/polo"
  ENABLE_OTEL: "true"
  BASE_URL_OTEL_COLLECTOR: "http://otel-collector-opentelemetry-collector.default:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marco
  labels:
    fluentd.logger: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marco
  template:
    metadata:
      labels:
        app: marco
        fluentd.logger: "true"
    spec:
      containers:
        - name: marco-app
          image: gm50x/marco
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: SERVICE_NAME
              value: "marco"
            - name: ROUTE_PREFIX
              value: "api/marco"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: NODE_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: LOG_FORMAT
            - name: MARCO_URL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: MARCO_URL
            - name: POLO_URL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: POLO_URL
            - name: ENABLE_OTEL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: ENABLE_OTEL
            - name: BASE_URL_OTEL_COLLECTOR
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: BASE_URL_OTEL_COLLECTOR
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: "rabbitmq"
                  key: "AMQP_URL"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: marco-service
spec:
  type: ClusterIP
  selector:
    app: marco
  ports:
    - name: marco-http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marco-srv-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: "/api/marco"
            pathType: Prefix
            backend:
              service:
                name: marco-service
                port:
                  number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polo
  labels:
    fluentd.logger: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polo
  template:
    metadata:
      labels:
        app: polo
        fluentd.logger: "true"
    spec:
      containers:
        - name: polo-app
          image: gm50x/polo
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: SERVICE_NAME
              value: "polo"
            - name: ROUTE_PREFIX
              value: "api/polo"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: NODE_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: LOG_FORMAT
            - name: MARCO_URL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: MARCO_URL
            - name: POLO_URL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: POLO_URL
            - name: ENABLE_OTEL
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: ENABLE_OTEL
            - name: BASE_URL_OTEL_COLLECTOR
              valueFrom:
                configMapKeyRef:
                  name: "common-marco-polo-config"
                  key: BASE_URL_OTEL_COLLECTOR
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: "rabbitmq"
                  key: "AMQP_URL"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: polo-service
spec:
  type: ClusterIP
  selector:
    app: polo
  ports:
    - name: polo-http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polo-srv-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: "/api/polo"
            pathType: Prefix
            backend:
              service:
                name: polo-service
                port:
                  number: 3000
