apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-volume
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    type: DirectoryOrCreate
    path: /var/lib/rancher/k3s/storage/rabbitmq
