---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  resources:
    requests:
      storage: 300Mi
  storageClassName: pg-local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.3-alpine3.20
          env:
            - name: "POSTGRES_USER"
              value: "gedai"
            - name: "POSTGRES_PASSWORD"
              value: "gedai"
            - name: "POSTGRES_DB"
              value: "gedai"
          ports:
            - name: pg
              containerPort: 5432
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip-srv
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - name: pgport
      protocol: TCP
      port: 5432
      targetPort: 5432
---
## TODO: add secret
