apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: gm50x/rabbitmq:3-management-delayed
          env:
            - name: "RABBITMQ_DEFAULT_USER"
              value: "gedai"
            - name: "RABBITMQ_DEFAULT_PASS"
              value: "gedai"

          ports:
            - name: rmq-mngt
              containerPort: 15672
            - name: rmq-amqp
              containerPort: 5672
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip-srv
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: rmq-mngt
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rmq-amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer-srv
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
    - name: rmq-mngt
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rmq-amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
